apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: v1.17a
      role: blue
  template:
    metadata:
      labels:
        app: nginx
        version: v1.17a
        role: blue
    spec:
      containers:
      - name: nginx-blue
        image: hub.test.io/app_v1.17a
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)